document.write("<h3>Rules for naming JS variables</h3>")
document.write("Variable names can only contain numbers,$ and_. For example $my_1stVariable. <br>")
document.write("Variables must begin with a letters,$ or,_.For example $name, _name or name <br>")
document.write("Variable names are case sensitive <br>")
document.write("Variable names should not be JS keyword <br>")